config/urls.py
from django.urls import path
from django.contrib import  admin
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('shopping/', include('shopping.urls')),
    path('accounts/', include('accounts.urls')),

]  + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('', homeView, name='home-view'),
    path('detail/<slug:slug>/', detailView, name='detail-view'),
    path('store/', store, name="store"),
    path('store/<slug:category_slug>/', category_productsView, name='category-products'),
    path('store/<slug:category_slug>/<slug:sub_cat_slug>/', sub_categoryView, name='subcategory-products'),
]

shopping/models.py
from django.db import models
from django.contrib.auth import get_user_model

from  store.models import Product



class Cart(models.Model):
    session_id = models.CharField(max_length=255,null=True)
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(verbose_name="yaratilgan sana",auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="O'zgartirilgan sana",auto_now=True)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(default=1)
    color = models.CharField(max_length=255, null=True)
    size = models.CharField(max_length=255, null=True)

    created_at = models.DateTimeField(verbose_name="yaratilgan sana",auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="O'zgartirilgan sana",auto_now=True)

    
    def total_price(self):
        return self.quantity * self.product.price

templates/index/banner.html
<!--START BANNER SECTION-->
<div class="banner-section parallax-slide">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-5 text-center">
                <div class="banner-content-wrapper">
                <span>TRENDING PRODUCT OF THE WEEK</span>
                <h1>Shirts Collections</h1>
                <p>Aenean imperdiet. Etiam ultricies nisi vel augue men tuhi spectrum alle me</p>
                 <button type="button" class="btn black-btn-with-border">SHOP NOW</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!--END BANNER SECTION-->

templates/index/base.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <!-- Author -->
    <meta name="author" content="Themes Industry">
    <!-- description -->
    <meta name="description" content="MegaOne is a highly creative, modern, visually stunning and Bootstrap responsive multipurpose studio and portfolio HTML5 template with 8 ready home page demos.">
    <!-- keywords -->
    <meta name="keywords" content="Creative, modern, clean, bootstrap responsive, html5, css3, portfolio, blog, studio, templates, multipurpose, one page, corporate, start-up, studio, branding, designer, freelancer, carousel, parallax, photography, studio, masonry, grid, faq">
    <!-- Page Title -->
    <title>Women Store | MegaOne HTML5 Template</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'shop/img/favicon.ico' %}">
    <!-- Bundle -->
    <link rel="stylesheet" href="{% static 'vendor/css/bundle.min.css' %}">
    <!-- Plugin Css -->
    <link rel="stylesheet" href="{% static 'vendor/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/cubeportfolio.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/wow.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/LineIcons.min.css' %}">
    <link rel="stylesheet" href="{% static 'shop/css/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'shop/css/range-slider.css' %}">
    <!-- Slider Setting Css  -->
    <link rel="stylesheet" href="{% static 'shop/css/settings.css' %}">
    <!-- Mega Menu  -->
    <link rel="stylesheet" href="{% static 'shop/css/megamenu.css' %}">
   
    <!-- Custom Css  -->
    <link rel="stylesheet" href="{% static 'shop/css/custom.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <!-- StyleSheet  -->
    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
</head>
</html>
{% block main %}
{% endblock main %}

templates/index/footer.html
<!--footer1 sec start-->
<div class="footer">
    <div class="container">
        <div class="row footer-container">
            <div class="col-sm-12 col-lg-4 f-sec1  text-center text-lg-left">
                <h4 class="high-lighted-heading">About Us</h4>
                <p>We take our mission of increasing our global access to quality education seriously. </p>
                <a href="#">Read more</a>
                <h4>Social Network</h4>
                <div class="s-icons">
                    <ul class="social-icons-simple">
                        <li><a href="javascript:void(0)" class="facebook-bg-hvr"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                        <li><a href="javascript:void(0)" class="twitter-bg-hvr"><i class="fab fa-twitter" aria-hidden="true"></i></a> </li>
                        <li><a href="javascript:void(0)" class="instagram-bg-hvr"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-12 col-lg-5 f-sec2 ">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <h4 class="text-center text-md-left">Information</h4>
                        <ul class="text-center text-md-left">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Delivery Information</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms & Condition</a></li>
                            <li><a href="#">FAQ</a></li>
                            <li><a href="shop/contact.html">Contact Us</a></li>
                            <li><a href="#">Products</a></li>
                        </ul>
                    </div>
                    <div class="col-12 col-md-6">
                        <h4 class="text-center text-md-left">Account Info</h4>
                        <ul class="text-center text-md-left">
                            <li><a href="#">Login & Register</a></li>
                            <li><a href="#">Order History</a></li>
                            <li><a href="#">Shipping Info</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Responsive Website</a></li>
                            <li><a href="#">Subscription</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-lg-3 f-sec3  text-center text-lg-left">
                <h4>Our Portfolio</h4>
                <div class="foot-tag-list">
                    <span>T-shirt</span>
                    <span>Casual</span>
                    <span>Shorts</span>
                    <span>Formal</span>
                    <span>Formal-Shirt</span>
                    <span>Shopping</span>
                    <span>Shirts</span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 footer_notes">
                <p class="whitecolor text-center w-100 wow fadeInDown">&copy; 2020 MegaOne. Made With Love by <a class="web-link" href="http://www.themesindustry.com/" target="_blank">Themesindustry</a></p>
            </div>
        </div>
    </div>
</div>
<!--foo0ter1 sec end-->

templates/index/header-top.html
{% load static %}
<!--START SEARCH AREA-->
<div class="search-box-overlay">
    <a><i class="fas fa-times cross-sign" id="close-window"></i></a>

    <div class="container">
        <div class="row">
            <div class="col-12 search-col">
                <form action="{% url 'store' %}">
                <div class="input-group search-box-form">
                    <input type="text" class="form-control" name="q" placeholder="Search Here" aria-label="Search Here">
                    <div class="input-group-prepend">
                        <button class="input-group-text" type="submit" id="basic-addon1"><i class="fas fa-search"></i></button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/index/index-shop.html
{% extends "index/base.html" %}
{% load static %}
{% block main %}

<body>

{% include "index/navigator.html" %}

<a class="scroll-top-arrow" href="javascript:void(0);"><i class="fa fa-angle-up"></i></a>
<!--START LOADER-->
<div class="loader1">
    <div class="loader-inner">
        <div id="preloader">
            <div id="loader"></div>
        </div>
    </div>
</div>
<!--END LOADER-->
{% include "index/header-top.html" %}

{% include "index/slider.html" %}

{% include "index/recommend-items.html" %}

{% include "index/laters-arrival.html" %}

{% include "index/banner.html" %}

{% include "index/footer.html" %} 

{% include "index/javaScript.html"  %}

</body>
{% endblock main %}

templates/index/javaScript.html
{% load static %}
<!-- JavaScript -->
<script src="{% static 'vendor/js/bundle.min.js' %}"></script>
<!-- Plugin Js -->
<script src="{% static 'vendor/js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'vendor/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/js/swiper.min.js' %}"></script>
<script src="{% static 'vendor/js/jquery.cubeportfolio.min.js' %}"></script>
<script src="{% static 'vendor/js/wow.min.js' %}"></script>
<script src="{% static 'vendor/js/bootstrap-input-spinner.js' %}"></script>
<script src="{% static 'vendor/js/parallaxie.min.js' %}"></script>
<script src="{% static 'vendor/js/stickyfill.min.js' %}"></script>
<script src="shop/js/nouislider.min.js' %}"></script>

<script src="{% static 'vendor/js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'vendor/js/jquery.themepunch.revolution.min.js' %}"></script>
<!-- SLIDER REVOLUTION EXTENSIONS -->
<script src="{% static 'vendor/js/extensions/revolution.extension.actions.min.js' %}"></script>
<script src="{% static 'vendor/js/extensions/revolution.extension.carousel.min.js' %}"></script>
<script src="{% static 'vendor/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
<script src="{% static 'vendor/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'vendor/js/extensions/revolution.extension.migration.min.js' %}"></script>
<script src="{% static 'vendor/js/extensions/revolution.extension.navigation.min.js' %}"></script>
<script src="{% static 'vendor/js/extensions/revolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'vendor/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'vendor/js/extensions/revolution.extension.video.min.js' %}"></script>

<!-- Custom Script -->
<script src="{% static 'shop/js/script.js' %}"></script>

templates/index/laters-arrival.html
{% load static %}
<!--START LATEST ARRIVALS-->
<div class="lastest_arrivals">
    <div class="container">
        <div class="row">
            <div class="col-12 mb-4">
                <h1>Latest Arrivals</h1>
            </div>

            <div class="col-12">
                <div class="lastest_featured_products owl-carousel owl-theme">
                    {% for product in products %}
                        <div class="lastest_arrival_items item">
                            <div class="card">
                                <span class="product-type">new</span>
                                <div class="image-holder">
                                    <a href="{% url 'detail-view' slug=product.slug %}"><img src="{% get_media_prefix %}{{product.image}}" class="card-img-top" alt="Lastest Arrivals 1"></a>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-12 text-center">
                                            <a href="{% url 'detail-view' slug=product.slug %}"><h5 class="card-title">{{product.name}}</h5></a>
                                        </div>
                                        <div class="col-12 text-center">
                                            <p class="card-text">{{product.price}} so'm</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>
<!--END LATEST ARRIVALS-->

templates/index/navigator.html
{% load static %}
<!-- START HEADER NAVIGATION -->
<div class="header-area">
    <div class="container">
        <div class="row upper-nav">

            <div class="col-3 nav-icon pt-3">
                <ul class="social-icons-simple text-left">
                    <li><a href="javascript:void(0)" class="facebook-bg-hvr"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                    <li><a href="javascript:void(0)" class="twitter-bg-hvr"><i class="fab fa-twitter" aria-hidden="true"></i></a> </li>
                    <li><a href="javascript:void(0)" class="instagram-bg-hvr"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
            </div>
            <div class="col-6 text-center nav-logo pt-3">
                <a href="index-shop.html" class="navbar-brand"><img src="{% static 'shop/img/logo.jpg' %}" alt="img"></a>
            </div>

            <div class="col-3 nav-utility text-right d-flex justify-content-end align-items-center pt-3">
                <div class="manage-icons d-inline-block">
                        <ul>
                            <li class="d-inline-block">
                                <a id="add_search_box">
                                    <i class="fas fa-search search-sidebar-hover"></i>
                                </a>
                            </li>
                            <li class="d-inline-block mini-menu-card" id="mini-menu-card">
                                <a class="nav-link collapsePagesSideMenu" data-toggle="collapse">
                                    <a href="{% url 'cart' %}">
                                        <i class="fas fa-shopping-cart"></i>    
                                    </a>
                                </a>
                                
                            </li>
                            <li class="d-inline-block simple-dropdown" id="mini-menu">
                                <a class="nav-link collapsePagesSideMenu" data-toggle="collapse" href="#sideNavPages5">
                                    <i class="fas fa-th"></i>
                                </a>

                                <div id="sideNavPages5" class="collapse sideNavPages user-utiliity">
                                    <i class="fas fa-caret-up user-utiliity-caret"></i>
                                    <h6 class="user-utiliity-title">MY ACCOUNT </h6>
                                    <hr>
                                    <ul class="text-left">
                                        <li>
                                            <a href="{% url 'account-register' %}">Register</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'account-login' %}">Login</a>
                                        </li>
                                    </ul>
                                </div>

                            </li>
                        </ul>
                 </div>
            </div>
            <div class="col-12 nav-mega">
                <header class="site-header" id="header">
                    <nav class="navbar navbar-expand-md  static-nav">
                        <div class="container position-relative megamenu-custom">
                            <a class="navbar-brand center-brand" href="index.html">
                                <img src="{% static 'shop/img/logo.jpg' %}" alt="logo" class="logo-scrolled">
                            </a>
                            <div class="collapse navbar-collapse">
                                <ul class="navbar-nav ml-auto mr-auto">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'home-view' %}">HOME</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'store' %}">STORE</a>
                                    </li>
                    
                                    {% for category in categories %}
                                    <li class="nav-item dropdown position-relative">
                                        <a class="nav-link dropdown-toggle" href="{% url 'category-products' category_slug=category.slug  %}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{category.title}}</a>
                                        <div class="dropdown-menu">
                                            {% for sub_cat in sub_cats %}
                                                {% if sub_cat.category == category %}
                                                    <ul>
                                                        <li><i class="lni-angle-double-right right-arrow"></i><a class="dropdown-item" href="{% url 'subcategory-products' category_slug=category.slug  sub_cat_slug=sub_cat.slug %}">{{sub_cat.name}}</a></li>
                                                    </ul>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </li>
                                    {% endfor %}

                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'contact' %}">CONTACT</a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    
                    </nav>
                </header>
            </div>
        </div>
    </div>
</div>
<!-- END HEADER NAVIGATION -->

templates/index/product-detail.html
{% extends 'index/base.html' %}

{% load static %}

{% block main %}

{% include "index/navigator.html" %}
<br>
<br>
<div class="pro-detail-sec row">
    <div class="col-12">
        <h4 class="pro-heading text-lg-left ">{{product.sub_category}}</h4>
    </div>
</div>
<br>
<div class="row product-list product-detail">
    <div class="col-12 col-lg-6 product-detail-slider">
        <div class="wrapper">
            <div class="Gallery swiper-container img-magnifier-container" id="gallery">
                <div class="swiper-wrapper myimgs">
                    <div class="swiper-slide"> <a href="{% get_media_prefix %}{{product.image}}" data-fancybox="1"
                            title="Zoom In"><img class="myimage" src="{% get_media_prefix %}{{product.image}}"
                                alt="gallery" /></a></div>
                </div>
            </div>
            <div class="Thumbs swiper-container" id="thumbs">
                <div class="swiper-wrapper">
                    {% for product_image in product.product_images.all %}
                    <div class="swiper-slide"> <a href="{% get_media_prefix %}{{product_image.image}}" data-fancybox="1"
                            title="Zoom In"> <img src="{% get_media_prefix %}{{product_image.image}}"
                                alt="thumnails" /></a></div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </aside>
    <main class="col-md-6">
        <article class="product-info-aside">

            <h2 class="title mt-3"></h2>

            <div class="mb-3">
                <var class="price h4">{{product.name}} </var>
            </div> <!-- price-detail-wrap .// -->

            <p>{{product.body}}</p>


            <input type="hidden" name="product_id" value="">
            <dl class="row">
                <dt class="col-sm-3">price</dt>
                <dd class="col-sm-9">{{product.price}} so'm</dd>

                <input type="hidden" name="product_id" value="{{product.id}}">
                <dl class="row">
                    <dt class="col-sm-3">Availabilty</dt>
                    {% if product.availabilty == True %}
                        <dd class="col-sm-9">in Stock</dd>
                    {% else  %}
                        <dd class="col-sm-9">out of Stock</dd>
                    {% endif %}  
                    <dt class="col-sm-3">Size</dt>
                    <dd class="col-sm-9">
                        <select name="size" id="id_size">
                            <option value="-1" selected>Choose size</option>
                            {% for size in product.product_size.all %}
                            <option value="{{size.id}}">{{size.name}}</option>
                            {% endfor %}
                        </select>
                    </dd>


                    <dt class="col-sm-3">Colors</dt>
                    <dd class="col-sm-9">
                        <select name="color" id="id_color">
                            <option value="-1">Choose color</option>
                            {% for color in product.product_colors.all %}
                            <option value="{{color.id}}">{{color.name}}</option>
                            {% endfor %}
                        </select>
                    </dd>
                </dl>


                <div class="form-row  mt-4">
                    <div class="form-group col-md">
                        <a href="{% url 'add-cart-item' product_id=product.id %}" class="btn  btn-primary" id="add_to_cart">
                            <i class="fas fa-shopping-cart"></i> <span class="text">Add to cart</span>
                        </a>
                        <a href="#" class="btn btn-light">
                            <i class="fas fa-envelope" style="color: chocolate;"></i> <span class="text" style="color: chocolate;">Contact supplier</span>
                        </a>
                    </div> <!-- col.// -->
                </div> <!-- row.// -->

        </article> <!-- product-info-aside .// -->
    </main> <!-- col.// -->
</div> <!-- row.// -->

{% include "index/header-top.html" %}

{% include "index/laters-arrival.html" %}

{% include "index/footer.html" %}

{% include "index/javaScript.html" %}

{% endblock main %}

templates/index/recommend-items.html
{% load static %}
<!-- START PORTOLIO SECTION -->
<div class="portfolio-section">
    <div class="container">
        <div class="row">

            <!-- START PORTFOLIO HEADING -->
            <div class="col-12">
                <div class="portfolioHeading text-center">
                    <h1 class="high-lighted-heading">Our Luxurious Product</h1>
                    <p>Aenean imperdiet. Etiam ultricies nisi vel augue men tuhi spectrum alle me.</p>
                </div>
            </div>
            <!-- END PORTFOLIO HEADING -->

                <!-- START FILTERS -->
            <div class="col-12">
                <div class="clearfix d-flex justify-content-center">
                    <div id="js-filters-blog-posts" class="cbp-l-filters-button cbp-1-filters-alignCenter">
                        <div data-filter="*" class="cbp-filter-item-active cbp-filter-item cbp-l-filters-list-first">All </div>
                        <div data-filter=".CausalShirts" class="cbp-filter-item">Causal Shirts </div>
                        <div data-filter=".others" class="cbp-filter-item cbp-l-filters-list-last">Others </div>
                    </div>
                </div>
            </div>
                <!-- END FILTERS -->

                <!-- START PORTFOLIO IMAGES -->
            <div class="col-12">
                <div id="js-grid-blog-posts" class="cbp">
                {% for product in products %}
                    <div class="cbp-item CausalShirts others wow slideInUp">
                        
                        <div class="image-holder">
                            <a href="{% url 'detail-view' slug=product.slug %}"><img src="{% get_media_prefix %}{{product.image}}" class="card-img-top" alt="Lastest Arrivals 1"></a>
                        </div>
                        <div class="row">
                            <div class="col-12 text-center">
                                <a href="{% url 'detail-view' slug=product.slug %}" target="_blank" class="cbp-l-grid-blog-title portfolio-title">{{product.name}}</a>
                            </div>
                            <div class="col-12 text-center">
                                <div class="cbp-l-grid-blog-desc portfolio-des">{{product.price}} so'm</div>
                            </div>
                        </div>
                    </div>
                {% endfor  %}

                </div>
            </div>
                <!-- END PORTFOLIO IMAGES -->

        </div>
    </div>
</div>
<!-- END PORTOLIO SECTION -->